Update GA Artifact to v4

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,20 +1,21 @@
-name: Continuous Integration on Master
+name: Continuous Integration on master branch
 on:
   push:
     branches:
     - master
-    - 36901
+    - develop
   pull_request:
     branches:
     - master
+    - develop
 env:
-  SOURCE_ARTIFACT: source
+  SOURCE_ARTIFACT: ${{ github.workspace }}/source
 jobs:
   create-source-distribution:
     name: Create Source Distribution
-    runs-on: ubuntu-22.04
+    runs-on: ubuntu-20.04
     env:
-      ARTIFACT_DIR: source
+      ARTIFACT_DIR: ${{ github.workspace }}/artifacts/source
     steps:
     - name: Checkout
       uses: actions/checkout@v2
@@ -32,7 +33,7 @@ jobs:
     - name: Create Distribution Tarball
       run: |
         ./autogen.sh
-        ./configure --with-incompatible-bdb --with-miniupnpc
+        ./configure --with-incompatible-bdb --with-miniupnpc CXXFLAGS="-std=c++11"
         make dist
     - name: Download Dependencies
       run: make -C depends download
@@ -41,66 +42,62 @@ jobs:
     - name: Prepare Files for Artifact
       run: |
         mkdir -p $ARTIFACT_DIR
-        mv depends.tar.gz cyberdollar-*.tar.gz $ARTIFACT_DIR
+        mv depends.tar.gz acash-*.tar.gz $ARTIFACT_DIR
     - name: Upload Artifact
-      uses: actions/upload-artifact@v1
+      uses: actions/upload-artifact@v4
       with:
-        name: ${{ env.SOURCE_ARTIFACT }}
+        name: source
         path: ${{ env.ARTIFACT_DIR }}
   build-linux:
     name: Build for Linux
     needs: create-source-distribution
-    runs-on: ubuntu-22.04
+    runs-on: ubuntu-20.04
     env:
-      ARTIFACT_DIR: linux-binaries
+      ARTIFACT_DIR: ${{ github.workspace }}/artifacts/linux
       TEST_LOG_ARTIFACT_DIR: test-logs
     steps:
     - name: Getting Source
-      uses: actions/download-artifact@v1
+      uses: actions/download-artifact@v4
       with:
-        name: ${{ env.SOURCE_ARTIFACT }}
+        name: source
     - name: Extract Archives
       run: |
         tar -xzf depends.tar.gz
-        tar -xzf cyberdollar-*.tar.gz --strip-components=1
-      working-directory: ${{ env.SOURCE_ARTIFACT }}
+        tar -xzf acash-*.tar.gz --strip-components=1
     - name: Install Required Packages
       run: |
         sudo apt-get update
         sudo apt-get install -y python3-zmq
     - name: Build Dependencies
       run: make -C depends -j$(nproc)
-      working-directory: ${{ env.SOURCE_ARTIFACT }}
-    - name: Build CyberDollar
+    - name: Build ACash
       run: |
-        ./configure --prefix=$(realpath depends/x86_64-pc-linux-gnu)
+        ./configure --prefix=$(realpath depends/x86_64-pc-linux-gnu) --disable-tests
         make -j$(nproc)
-      working-directory: ${{ env.SOURCE_ARTIFACT }}
     - name: Prepare Files for Artifact
       run: |
         mkdir -p $ARTIFACT_DIR
-        mv $SOURCE_ARTIFACT/src/{cyberdollar-cli,cyberdollar-tx,cyberdollard,qt/cyberdollar-qt} $ARTIFACT_DIR
+        mv ./src/{acash-cli,acash-tx,acashd,qt/acash-qt} $ARTIFACT_DIR
     - name: Upload Artifact
-      uses: actions/upload-artifact@v1
+      uses: actions/upload-artifact@v4
       with:
         name: linux-binaries
         path: ${{ env.ARTIFACT_DIR }}
   build-windows:
     name: Build for Windows
     needs: create-source-distribution
-    runs-on: ubuntu-22.04
+    runs-on: ubuntu-20.04
     env:
-      ARTIFACT_DIR: windows-binaries
+      ARTIFACT_DIR: ${{ github.workspace }}/artifacts/windows
     steps:
     - name: Getting Source
-      uses: actions/download-artifact@v1
+      uses: actions/download-artifact@v4
       with:
-        name: ${{ env.SOURCE_ARTIFACT }}
+        name: source
     - name: Extract Archives
       run: |
         tar -xzf depends.tar.gz
-        tar -xzf cyberdollar-*.tar.gz --strip-components=1
-      working-directory: ${{ env.SOURCE_ARTIFACT }}
+        tar -xzf acash-*.tar.gz --strip-components=1
     - name: Install Required Packages
       run: |
         sudo apt-get update
@@ -111,86 +108,84 @@ jobs:
         sudo update-alternatives --set x86_64-w64-mingw32-g++ /usr/bin/x86_64-w64-mingw32-g++-posix
     - name: Build Dependencies
       run: make -C depends -j$(nproc) HOST=x86_64-w64-mingw32
-      working-directory: ${{ env.SOURCE_ARTIFACT }}
-    - name: Build CyberDollar
+    - name: Build ACash
       run: |
         ./configure --prefix=$(realpath depends/x86_64-w64-mingw32)
         make -j$(nproc)
-      working-directory: ${{ env.SOURCE_ARTIFACT }}
     - name: Prepare Files for Artifact
       run: |
         mkdir -p $ARTIFACT_DIR
-        mv $SOURCE_ARTIFACT/src/{cyberdollar-cli.exe,cyberdollar-tx.exe,cyberdollard.exe,qt/cyberdollar-qt.exe} $ARTIFACT_DIR
+        mv ./src/{acash-cli.exe,acash-tx.exe,acashd.exe,qt/acash-qt.exe} $ARTIFACT_DIR
     - name: Upload Artifact
-      uses: actions/upload-artifact@v1
+      uses: actions/upload-artifact@v4
       with:
         name: windows-binaries
         path: ${{ env.ARTIFACT_DIR }}
 
   # MacOS build script adapted from https://github.com/dogecoin/dogecoin/blob/master/.github/workflows/ci.yml
-  build-macos:
-    name: Build for MacOS
-    needs: create-source-distribution
-    runs-on: ubuntu-22.04
-    env:
-      name: x86_64-macos
-      host: x86_64-apple-darwin11
-      os: ubuntu-22.04
-      packages: cmake imagemagick libcap-dev librsvg2-bin libz-dev libtiff-tools libtinfo5 python3-setuptools xorriso libtinfo5
-      config-opts: "--enable-gui=qt5 --enable-reduce-exports"
-      goal: deploy
-      sdk: 10.11
-      sdk-url: "https://bitcoincore.org/depends-sources/sdks"
-    steps:
-      - name: Install packages
-        run: |
-          sudo apt-get update
-          sudo apt-get install build-essential libtool autotools-dev automake pkg-config bsdmainutils curl ca-certificates ccache python3 rsync git procps bison
-          sudo apt-get install ${{ env.packages }}
-      - name: Checkout
-        uses: actions/checkout@v2
-      - name: SDK cache
-        if: ${{ env.sdk }}
-        uses: actions/cache@v2
-        env:
-          cache-name: sdk
-        with:
-          path: ./depends/sdk-sources
-          key: ${{ env.name }}-${{ env.cache-name }}
-      - name: Install SDK
-        if: ${{ env.sdk }}
-        run: |
-          mkdir -p ./depends/sdk-sources
-          mkdir -p ./depends/SDKs
-          curl --location --fail ${{ env.sdk-url }}/MacOSX${{ env.sdk }}.sdk.tar.gz -o depends/sdk-sources/MacOSX${{ env.sdk }}.sdk.tar.gz
-          tar -C depends/SDKs -xf depends/sdk-sources/MacOSX${{ env.sdk }}.sdk.tar.gz
-      - name: Dependency cache
-        uses: actions/cache@v2
-        env:
-          cache-name: depends
-        with:
-          path: ./depends/built
-          key: ${{ env.name }}-${{ env.cache-name }}-${{ hashFiles('depends/packages/*') }}
-      - name: Build depends
-        run: |
-          make -C depends HOST=${{ env.host }}
-      - name: CCache
-        uses: actions/cache@v2
-        env:
-          cache-name: ccache
-        with:
-          path: ~/.ccache
-          key: ${{ env.name }}-${{ env.cache-name }}-${{ hashFiles('**/configure.ac') }}
-      - name: Build CyberDollar
-        run: |
-          depends/${{ env.host }}/native/bin/ccache --max-size=100M
-          ./autogen.sh
-          ./configure --prefix=`pwd`/depends/${{ env.host }} ${{ env.config-opts }} || ( cat config.log && false)
-          make ${{ env.goal }} || ( echo "Build failure. Verbose build follows." && make ${{ env.goal }} V=1 ; false )
-          mv CyberDollar-Core.dmg CyberDollar.dmg
-      - name: Upload artifacts
-        uses: actions/upload-artifact@v2
-        with:
-          name: macos-binaries
-          path: |
-            CyberDollar.dmg
+  # build-macos:
+  #   name: Build for MacOS
+  #   needs: create-source-distribution
+  #   runs-on: ubuntu-20.04
+  #   env:
+  #     name: x86_64-macos
+  #     host: x86_64-apple-darwin11
+  #     os: ubuntu-20.04
+  #     packages: cmake imagemagick libcap-dev librsvg2-bin libz-dev libtiff-tools libtinfo5 python3-setuptools xorriso libtinfo5
+  #     config-opts: "--enable-gui=qt5 --enable-reduce-exports"
+  #     goal: deploy
+  #     sdk: 10.11
+  #     sdk-url: "https://bitcoincore.org/depends-sources/sdks"
+  #   steps:
+  #     - name: Install packages
+  #       run: |
+  #         sudo apt-get update
+  #         sudo apt-get install build-essential libtool autotools-dev automake pkg-config bsdmainutils curl ca-certificates ccache python3 rsync git procps bison
+  #         sudo apt-get install ${{ env.packages }}
+  #     - name: Checkout
+  #       uses: actions/checkout@v2
+  #     - name: SDK cache
+  #       if: ${{ env.sdk }}
+  #       uses: actions/cache@v2
+  #       env:
+  #         cache-name: sdk
+  #       with:
+  #         path: ./depends/sdk-sources
+  #         key: ${{ env.name }}-${{ env.cache-name }}
+  #     - name: Install SDK
+  #       if: ${{ env.sdk }}
+  #       run: |
+  #         mkdir -p ./depends/sdk-sources
+  #         mkdir -p ./depends/SDKs
+  #         curl --location --fail ${{ env.sdk-url }}/MacOSX${{ env.sdk }}.sdk.tar.gz -o depends/sdk-sources/MacOSX${{ env.sdk }}.sdk.tar.gz
+  #         tar -C depends/SDKs -xf depends/sdk-sources/MacOSX${{ env.sdk }}.sdk.tar.gz
+  #     - name: Dependency cache
+  #       uses: actions/cache@v2
+  #       env:
+  #         cache-name: depends
+  #       with:
+  #         path: ./depends/built
+  #         key: ${{ env.name }}-${{ env.cache-name }}-${{ hashFiles('depends/packages/*') }}
+  #     - name: Build depends
+  #       run: |
+  #         make -C depends HOST=${{ env.host }}
+  #     - name: CCache
+  #       uses: actions/cache@v2
+  #       env:
+  #         cache-name: ccache
+  #       with:
+  #         path: ~/.ccache
+  #         key: ${{ env.name }}-${{ env.cache-name }}-${{ hashFiles('**/configure.ac') }}
+  #     - name: Build ACash
+  #       run: |
+  #         depends/${{ env.host }}/native/bin/ccache --max-size=100M
+  #         ./autogen.sh
+  #         ./configure --prefix=`pwd`/depends/${{ env.host }} ${{ env.config-opts }} || ( cat config.log && false)
+  #         make ${{ env.goal }} || ( echo "Build failure. Verbose build follows." && make ${{ env.goal }} V=1 ; false )
+  #         mv ACash-Core.dmg ACash.dmg
+  #     - name: Upload artifacts
+  #       uses: actions/upload-artifact@v4
+  #       with:
+  #         name: macos-binaries
+  #         path: |
+  #           ACash.dmg
